services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 10s

  server:
    build:
      target: dev
      context: .
      dockerfile: ./apps/collab-server/Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=1234
      - DATABASE_URL=mysql://root:${DATABASE_PASS}@database/${DATABASE_NAME}
    ports:
      - "1234:1234"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - "./apps/collab-server/src:/app/apps/collab-server/src"
