import Head from "next/head";
import Paper from "../components/Paper";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>MD editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid min-h-screen grid-cols-[1fr_3fr]">
        <Sidebar className="sticky top-0 left-0 bg-blue-300" />
        <main className="p-4">
          <Paper />
        </main>
      </div>
    </>
  );
}
