import dynamic from "next/dynamic";
import Head from "next/head";
import Container from "../components/Container";

const Paper = dynamic(() => import("../components/Paper"), {
  // Disable server side rendering, because of WebSocket API
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>MD editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-100">
        <Container>
          <Paper />
        </Container>
      </main>
    </>
  );
}
